### PR TITLE
Avoids adding duplicated items

### LINKED ISSUE #430: Fix: do not allow several time the same item among item children
In item edit, it is currently possible to add several time the same item in the list, it will fail at "save". The UI should prevent that early.  For that, the search component should receive the list of `id` "already added" and replace the "+ add" button by a greyed-out "already added" one when the search result is in this list.

### PR DESCRIPTION
**Pull request by Iloveall**
Fixes #430

### CODE REVIEW

File: src/app/modules/shared-components/components/add-content/add-content.component.ts [hunk 1]
```diff
@@ -29,7 +29,9 @@ export class AddContentComponent<Type> implements OnInit, OnDestroy {
   @Input() allowedTypesForNewContent: NewContentType<Type>[] = [];
   @Input() searchFunction?: (searchValue: string) => Observable<AddedContent<Type>[]>;
   @Input() loading = false;
+  @Input() addedItemIds: string[] = [];
```
Comment (smadbe) [inline src/app/modules/shared-components/components/add-content/add-content.component.ts:32]: Add content component is not item specific !

File: src/app/modules/item/components/item-children-edit/item-children-edit.component.ts [hunk 2]
```diff
@@ -107,10 +112,19 @@ export class ItemChildrenEditComponent implements OnChanges {
...
     this.data = this.data.map(c => ({ ...c, scoreWeight: DEFAULT_SCORE_WEIGHT }));
+    this.onChildAdded();
     this.onScoreWeightChange();
   }
 
   onScoreWeightChange(): void {
     this.childrenChanges.emit(this.data);
   }
+
+  onChildAdded(): void {
```
Comment (smadbe) [inline src/app/modules/item/components/item-children-edit/item-children-edit.component.ts:123]: You call in `onRemove` so it is not really `onChildAdded`.
`onChildrenListUpdate"? Actually as it is a function and not really a button callback I would call it by what it does, so "recomputeAddedIds". 
... but it must be called together with the data update, not forgetting any case, otherwise you would have an inconsistent state... I think that would be cleaner to just use the map in the template.

**Review by smadbe — CHANGES_REQUESTED** [review]

File: src/app/modules/shared-components/components/add-content/add-content.component.ts (hunk 1 above)
Comment (Iloveall) [reply src/app/modules/shared-components/components/add-content/add-content.component.ts]: Fixed

File: src/app/modules/item/components/item-children-edit/item-children-edit.component.ts (hunk 2 above)
Comment (Iloveall) [reply src/app/modules/item/components/item-children-edit/item-children-edit.component.ts:123]: I prefer onChildrenListUpdate as it common pattern, also it could be extended in future for another on updated operations.

File: src/app/modules/item/components/item-children-edit/item-children-edit.component.ts [hunk 3]
```diff
@@ -107,10 +112,19 @@ export class ItemChildrenEditComponent implements OnChanges {
...
     this.data = this.data.map(c => ({ ...c, scoreWeight: DEFAULT_SCORE_WEIGHT }));
+    this.onChildrenListUpdate();
     this.onScoreWeightChange();
   }
 
   onScoreWeightChange(): void {
     this.childrenChanges.emit(this.data);
   }
+
+  onChildrenListUpdate(): void {
```
Comment (smadbe) [inline src/app/modules/item/components/item-children-edit/item-children-edit.component.ts:123]: should be private I assume

File: src/app/modules/item/components/item-children-edit/item-children-edit.component.ts [hunk 4]
```diff
@@ -107,10 +112,19 @@ export class ItemChildrenEditComponent implements OnChanges {
...
+    this.addedItemIds = this.getAddedItemIds();
+  }
+
+  getAddedItemIds(): string[] {
+    return this.data.map(item => item.id).filter(isNotUndefined);
```
Comment (smadbe) [inline src/app/modules/item/components/item-children-edit/item-children-edit.component.ts:128]: If used at a single place, I prefer you put this code directly it is used. (this should not have used outside setting the new value to this.addedItemIds).
(alternatively, you call your function "recomputeAddedItemIds" and this function assign the value directly.

**Review by smadbe — CHANGES_REQUESTED** [review]
small remarks

File: src/app/modules/item/components/item-children-edit/item-children-edit.component.ts (hunk 3 above)
Comment (Iloveall) [reply src/app/modules/item/components/item-children-edit/item-children-edit.component.ts:123]: Fixed

File: src/app/modules/item/components/item-children-edit/item-children-edit.component.ts (hunk 4 above)
Comment (Iloveall) [reply src/app/modules/item/components/item-children-edit/item-children-edit.component.ts:128]: Fixed

File: src/app/modules/item/components/item-children-edit/item-children-edit.component.ts [hunk 5]
```diff
@@ -107,10 +112,19 @@ export class ItemChildrenEditComponent implements OnChanges {
...
 
   onScoreWeightChange(): void {
     this.childrenChanges.emit(this.data);
   }
+
+  private onChildrenListUpdate(): void {
+    this.recomputeAddedItemIds();
+  }
+
+  recomputeAddedItemIds(): void {
```
[the remark this answers is not in the document]
Comment (Iloveall) [reply src/app/modules/item/components/item-children-edit/item-children-edit.component.ts]: Fixed
