### PR TITLE
Fixes break lines for thread message

### LINKED ISSUE #1513: [Bug] Forum: line break not display
## Overview

This message has a line break between the two words:
Screenshot 2023-10-05 at 16 12 03
... however it not shown

On [this task](https://dev.algorea.org/en/a/6379723280369399253;p=7528142386663912287,7523720120450464843;a=0) as the usual user

### PR DESCRIPTION
**Pull request by Iloveall**
## Description

Fixes #1513

## Notes (out of scope, known isues, hints for reviewing code, ...)  (optional)

...

## Test cases

- [ ] Case 1:
  1. Given I am the usual user
  2. When I go to [this page](https://dev.algorea.org/branch/bugfix/forum-line-break-not-display/en/a/6379723280369399253;p=4702,1625159049301502151,5207993233955027100;pa=0)
  3. And I click on open the thread button
  4. Then I see messages with break like

### CODE REVIEW

File: src/app/shared/pipes/allowDisplayCodeSnippet.ts [hunk 1]
```diff
@@ -17,6 +17,6 @@ export class AllowDisplayCodeSnippet implements PipeTransform {
       return matchedWithTripleQuotes ? `
         <pre class="alg-code-wrapper"><code class="alg-code ${ theme }">${ matchedWithTripleQuotes }</code></pre>
       ` : matchedWithSingleQuotes ? `<code class="alg-code with-bg ${ theme }">${ matchedWithSingleQuotes }</code>` : '';
-    });
+    }).replace(/(\r\n|\n|\r)/gm, '<br>');
```
Comment (smadbe) [inline src/app/shared/pipes/allowDisplayCodeSnippet.ts:20]: It is not really related with `allowDisplayCodeSnippet` ... if we were to disable code snippet, we would probably still need line breaks. I think it should be in another pipe.

**Review by smadbe — CHANGES_REQUESTED** [review]

**Review by smadbe — APPROVED** [review]
