### PR TITLE
Fixes scroll to inside iframe

### LINKED ISSUE #1330: Bug: task scroll not working after a resize
**Describe the bug**

After a window resize, the scrolling inside a task does not work properly anymore. 

**To Reproduce**
1. As the usual user
2. Go to https://dev.algorea.org/en/a/5515805070397494516;p=7528142386663912287,7523720120450464843,6963488196048051083;a=0
3. Click on 'test scroll 1000'
4. I works
5. Resize the browser window, just a bit
6. Go up and click  'test scroll 1000'
7. I scroll to the top of the page instead of scrolling down

### PR DESCRIPTION
**Pull request by Iloveall**
## Description

Fixes #1330

## Notes (out of scope, known isues, hints for reviewing code, ...)  (optional)

It somehow related to `platformScrollTo` function here https://fioi.mblockelet.info/tests/bebras-modules/pemFioi/static-task.js

## Test cases

- [ ] Case 1:
  1. Given I am the usual user
  2. When I go to [this page](https://dev.algorea.org/en/a/5515805070397494516;p=7528142386663912287,7523720120450464843,6963488196048051083;a=0)
  3. And I click on "test scroll 1000"
  4. Then I see scroll to element
  5. And do resize browser and I do scroll to up
  6. And I click on "test scroll 1000"
  7. Then I see scroll to element

### CODE REVIEW

File: src/app/shared/directives/full-height-content.directive.ts [hunk 1]
```diff
@@ -36,7 +36,6 @@ export class FullHeightContentDirective implements AfterViewChecked, OnChanges {
 
   setHeight(): void {
     const top = this.el.nativeElement.getBoundingClientRect().top + globalThis.scrollY;
-    this.renderer.removeStyle(this.el.nativeElement, 'height');
```
Comment (Iloveall) [inline src/app/shared/directives/full-height-content.directive.ts:39]: I don't remember what for we kept it, but it works as before
