### PR TITLE
Feature/fix i18n texts

### LINKED ISSUE #902: Fix some i18n texts
* "You have delete "{groupName}"" -> "You have delete**d** "{groupName}"
* "... (not implemented)"-> the "not implemented" should be a separated string to be translated, not included with the field label
* "It usually occurs when task url is invalid, if the task url is valid and the problem persists, please contact us." -> "It usually occurs when task url is invalid. If the task url is valid and the problem persists, please contact us."
* "Your current progress could not have been saved. Are you connected to the internet ?" -> "Your current progress could not have been saved. Are you connected to the internet?" (last space)
* "If the problem persists contact us." ,  "If the problem persists, please contact us."(sometimes with typos) are used at many places, use an id (check i18n doc) to make sure there is only one translated string.
* "Leave the group ?" -> "Leave the group?" (last space)
* Unable to remove the selected manager(s). {result.errorText || ''} -> I suppsose the `result.errorText || ''` should be out of the translated text
* Same for {result.countSuccess} gestionnaire(s) ont été retiré(s), {result.countRequests - result.countSuccess} n'ont pas
       pu être retiré(s). {result.errorText || ''
* Is is on purpose that `i18n-pTooltip pTooltip="{{ 'Your current access rights do not allow you to list the content of this chapter.' }}"` is an interpreted string and not the string directly?
* "Invalid url "{url}": please provide an http link" -> "Invalid url "{url}": please provide an http(s) link"
* "Unable to load this task. Either you have a connexion issue or this task is not correctly configured. Please retry, if the problem persists, contact us." -> "Unable to load this task. Either you have a **connection** issue or this task is not correctly configured. Please retry, if the problem persists, contact us."
* This task is not correctly configured (chapter with task expected). -> This task is not correctly configured (chapter with tasks expected).
* ` {{ item.type === 'Chapter' ? 'Only empty chapters can be deleted.' : 'Only empty skills can be deleted.' }} ` -> create two separated translations 
* `Root activity: {{ rootActivityState.data.string.title }}` -> probably the translation can only be on  `Root activity:`
* `This group has no activity.` -> `This group has no root activity.`
* `<span>Given by</span><a                   class="alg-link"                   [routerLink]="{ id: grantedPermission.sourceGroup.id, isUser: false } | groupLink"                 > {{ grantedPermission.sourceGroup.name }} </a>` -> I assume only "Given by" should be i18n
* "This group has no permissions." -> "This group has no specific permissions."
* `"Sex"` -> "Gender"
* `Are you sure to remove from yourself the permission to edit group settings and edit managers ? ` -> `Are you sure to remove from yourself the permission to edit group settings and edit managers? ` (last space)
* `Non-visible content ({{ rowData.id }})` , only the first part should be part of the translation
* `Error while loading the children item` -> Error while loading the children item**s**
* `Unable to remove the selected group(s). {result.errorText || ''}` -> translation on the first part only?
* `{result.countSuccess} group(s) have been removed, {result.countRequests - result.countSuccess} could    not be removed. {result.errorText || ''}` same
* (reset current expiration) is repeated several time, it can be a single translatable text
* Add a description (see i18n doc) for the translatable "Load" (in item-log-view): "text on button to load a submission"
* Add a description (see i18n doc) for the translatable "User" (in group-log-view): "User column label"
* description for "Login of a user" -> "Placeholder of field for searching for user by login"
* description for "Not started" -> "In progress matrix, explanation when cell is empty"
* description for "# subm." -> "Truncated title (little space available) for 'number of submissions'"
* description for "Join" -> "Button label for joining a group"
* description for "Access" in item-details: -> "Button label for joining an item by (group) code"

### PR DESCRIPTION
**Pull request by Iloveall**
## Description

Fixes #902

## Notes (out of scope, known isues, hints for reviewing code, ...)  (optional)

...

## Test cases

- [ ] Case 1:
  1. Given I am the usual user
  2. When I go to [this page](https://dev.algorea.org/branch/feature/fix-i18n-texts/en/#/activities/by-id/1980584647557587953;path=4702,4102;attempId=0/edit/advanced-parameters)
  4. Then I see multiply (not implemented) captions

- [ ] Case 2:
  1. Given I am the usual user
  2. When I go to [this page](https://dev.algorea.org/en/#/activities/by-id/4702;path=;parentAttempId=0/details)
  4. Switch network to 3g and refresh browser.
  5. While loading turn network to offline
  6. Then I see "If this problem persists, please contact us." as before

- [ ] Case 3:
  1. Given I am the usual user
  2. When I go to [this page](https://dev.algorea.org/en/#/activities/by-id/1255005899678464217;path=39530140456452546,842524168135900505;attempId=0/details/progress/history)
  4. Switch network to offline and click on Content tab
  6. Then I see "An unknown error occurred. If this problem persists, please contact us."

- [ ] Case 4:
  1. Given I am the usual user
  2. When I go to [this page](https://dev.algorea.org/en/#/groups/by-id/672913018859223173;path=52767158366271444/details/members)
  4. Scroll down to Let user join using a code section
  6. Then hover on Validity: each buttons 
  7. Then I see tooltip with part of text (reset current expiration)
  8. Click on Custom button
  9. Hover on checked button
  10. Then I see tooltip with part of text (reset current expiration)

- [ ] Case 5:
  1. Given I am the usual user
  2. When I go to [this page](https://dev.algorea.org/en/#/activities/by-id/39530140456452546;path=4702,4102,1980584647557587953;attempId=0/edit/advanced-parameters)
  4. Scroll down to bottom 
  6. Then I see "Only empty chapters can be deleted."

- [ ] Case 6:
  1. Given I am the usual user
  2. When I go to [this page](https://dev.algorea.org/en/#/skills/by-id/7164018311292249641;path=3000,3002,2518359812137710892;attempId=0/edit/advanced-parameters)
  4. Scroll down to bottom 
  6. Then I see "Only empty skills can be deleted."

### CODE REVIEW

File: src/app/modules/group/components/member-list/group-removal-response-handling.ts [hunk 1]
```diff
@@ -10,11 +10,11 @@ export function displayGroupRemovalResponseToast(feedbackService: ActionFeedback
   if (result.countSuccess === result.countRequests) {
     feedbackService.success($localize`${result.countSuccess} group(s) have been removed`);
   } else if (result.countSuccess === 0) {
-    feedbackService.error($localize`Unable to remove the selected group(s). ${result.errorText || ''}`);
+    feedbackService.error($localize`Unable to remove the selected group(s). ` + `${result.errorText || ''}`);
```
Comment (ThomasJuster) [inline src/app/modules/group/components/member-list/group-removal-response-handling.ts:13]: Same as upper

File: src/app/modules/group/components/member-list/group-removal-response-handling.ts [hunk 2]
```diff
@@ -10,11 +10,11 @@ export function displayGroupRemovalResponseToast(feedbackService: ActionFeedback
...
   } else {
     feedbackService.partial(
       $localize`${result.countSuccess} group(s) have been removed, ${result.countRequests - result.countSuccess} could
-       not be removed. ${result.errorText || ''}`
+       not be removed. ` + `${result.errorText || ''}`
```
Comment (ThomasJuster) [inline src/app/modules/group/components/member-list/group-removal-response-handling.ts:17]: Same as upper

File: src/app/modules/group/components/group-join-by-code/group-join-by-code.component.html [hunk 3]
```diff
@@ -66,7 +66,7 @@
             class="submit-duration-button"
             (click)="codeLifetimeControlValue && submitCodeLifetime(codeLifetimeControlValue.ms)"
             [disabled]="processing || !codeLifetimeControlValue || !control.dirty || codeLifetimeControlValue.ms === group.codeLifetime?.ms"
-            i18n-pTooltip pTooltip="This code will expire after the given duration (reset current expiration)"
+            [pTooltip]="durationTooltip"
```
Comment (ThomasJuster) [inline src/app/modules/group/components/group-join-by-code/group-join-by-code.component.html:69]: Is there a reason not to use the i18n metadata via attribute `i18n-pTooltip="@@resetCurrentExpiration"` ?

File: src/app/modules/item/pages/item-display/item-display.component.html [hunk 4]
```diff
@@ -20,7 +20,7 @@
       <ng-template #unknownError>
         <alg-error
           *ngIf="unknownError$ | async as error"
-          i18n-message message="An unknown error occurred. If this problem persists, please contact us."
+          [message]="errorMessage"
```
Comment (ThomasJuster) [inline src/app/modules/item/pages/item-display/item-display.component.html:23]: (Same about the i18n metadata via attribute)

File: src/locale/messages.fr.xlf [hunk 5]
```diff
@@ -9,9 +9,31 @@
         <source>Oops, we are unable to make the site work properly. Are you connected to the Internet?</source><target state="translated">Impossible de démarrer une session. Êtes-vous bien connecté à Internet ?</target>
```
Comment (ThomasJuster) [inline src/locale/messages.fr.xlf]: @smadbe with such a task, a lot of translations will be lost :confused: 
Do we have to rework the french translation file **before** merging ?

**Review by ThomasJuster — COMMENTED** [review]
Very meticulous work :+1: 
Many comments are redundant and act as "post-it" so that I'm sure not to forget anything.

File: src/locale/messages.fr.xlf (hunk 5 above)
Comment (smadbe) [reply src/locale/messages.fr.xlf]: I will redo them, no problem.

File: src/app/modules/group/components/group-join-by-code/group-join-by-code.component.html (hunk 3 above)
Comment (ThomasJuster) [reply src/app/modules/group/components/group-join-by-code/group-join-by-code.component.html:69]: Comment after talking with @Iloveall: Because the translation is split into 2 parts and the attribute does not allow translation splitting

File: src/app/modules/lti/pages/lti/lti.component.html [hunk 6]
```diff
@@ -2,19 +2,19 @@
...
     *ngIf="error === 'no_item_or_explicit_entry_with_no_result'"
     i18n-message message="This task is not correctly configured (item not found or explicit entry but no result)"
   ></alg-error>
-  <alg-error *ngIf="error === 'login_error'" i18n>
-    Something wrong occurred during the login process, please retry after closing this tab or window.
+  <alg-error *ngIf="error === 'login_error'">
+    <ng-container i18n>Something wrong occurred during the login process, please retry after closing this tab or window.</ng-container>
     <br>
-    If the problem persists, please contact us.
+    <ng-container i18n="@@contactUs">If this problem persists, please contact us.</ng-container>
```
[the remark this answers is not in the document]
Comment (Iloveall) [reply src/app/modules/lti/pages/lti/lti.component.html]: Fixed

File: src/app/modules/group/components/group-manager-list/group-manager-removal-response-handling.ts [hunk 7]
```diff
@@ -5,11 +5,11 @@ export function displayGroupManagerRemovalResponseToast(feedbackService: ActionF
   if (result.countSuccess === result.countRequests) {
     feedbackService.success($localize`${result.countSuccess} manager(s) have been removed`);
   } else if (result.countSuccess === 0) {
-    feedbackService.error($localize`Unable to remove the selected manager(s). ${result.errorText || ''}`);
+    feedbackService.error($localize`Unable to remove the selected manager(s). ` + `${result.errorText || ''}`);
```
[the remark this answers is not in the document]
Comment (ThomasJuster) [reply src/app/modules/group/components/group-manager-list/group-manager-removal-response-handling.ts:8]: Erf, I guess that is linked to `$localize` being typed as any (only in dev env and not in CI, for some reason :thinking:)
We should investigate that issue, but that's obviously not for this PR.
Resolving

**Review by ThomasJuster — APPROVED** [review]
