### PR TITLE
Fixes scroll logic in left menu

### LINKED ISSUE #1109: Fix left menu auto-scroll
**Describe the bug**
When navigating to a element which is not visible in the left menu, the left menu should scroll to it. It was working but [the code](https://github.com/France-ioi/AlgoreaFrontend/blob/master/src/app/core/components/left-menu/left-menu.component.ts#L18) is not working anymore.

https://user-images.githubusercontent.com/1053150/180462206-3965955c-58bd-444d-8abc-938570eed178.mov

A part of the issue is because the left nav tree is using `id="nav-{{ node.data.id }}"` which is not defined anymore. It should use `id="nav-{{ node.data.route.id }}"`.  But this is not the only issue.
If it is not complicated, it would be useful to have some e2e test for that as it may be easily be re-broken without noticing.

### PR DESCRIPTION
**Pull request by Iloveall**
## Description

Fixes #1109

## Notes (out of scope, known isues, hints for reviewing code, ...)  (optional)

As we are going to migrate to another e2e platform, better to write the test for this task by after migration. The [issue](https://github.com/France-ioi/AlgoreaFrontend/issues/1121)

## Test cases

- [x] Case 1:
  1. Given I am the usual user
  2. And I set browser height about 450px
  3. When I go to [this page](https://dev.algorea.org/branch/bugfix/left-menu-scroll-to-element/en/#/activities/by-id/1352246428241737349;path=;attempId=0/details)
  4. Then I see scroll down to the "SNT (via group 'Managers DemoSNT')" item of menu

- [x] Case 2:
  1. Given I am the usual user
  2. And I set browser height about 450px
  3. When I go to [this page](https://dev.algorea.org/branch/bugfix/left-menu-scroll-to-element/en/#/activities/by-id/1768448808492845836;path=4702,4102;attempId=0/details)
  4. Then I click on next button of neighbours component
  5. Then I see scroll down to the "L1S1 Soutien informatique" item of menu

- [ ] Case 3:
  1. Given I am the usual user
  2. And I set browser height about 450px
  3. When I go to [this page](https://dev.algorea.org/branch/bugfix/left-menu-scroll-to-element/en/#/skills/by-id/1133373964112078654;path=3000,3002;attempId=0/details)
  4. Then I click on next button of neighbours component several times until "L1S1 Soutien informatique"
  5. Then I see scroll down until "Skill For delete" became visible enough 

- [x] Case 4:
  1. Given I am the usual user
  2. And I set browser height about 450px
  3. When I go to [this page](https://dev.algorea.org/branch/bugfix/left-menu-scroll-to-element/en/#/skills/by-id/3001;path=3000,3002;attempId=0/details)
  4. Then I click on next button of neighbours component
  5. Then I see scroll down to the "Skill For delete" item of menu

- [x] Case 5:
  1. Given I am the usual user
  2. And I set browser height about 450px
  3. When I go to [this page](https://dev.algorea.org/branch/bugfix/left-menu-scroll-to-element/en/#/groups/by-id/6884210558506774905;path=/details)
  4. Then I see scroll down to the "DemoSNT" item of menu

- [x] Case 6:
  1. Given I am the usual user
  2. And I set browser height about 450px
  3. When I go to [this page](https://dev.algorea.org/branch/bugfix/left-menu-scroll-to-element/en/#/groups/by-id/5648167580972785132;path=/details)
  4. Then I click on next button of neighbours component
  5. Then I see scroll down to the "ControleS2-2019" item of menu

### CODE REVIEW

File: src/app/core/components/left-menu/left-menu.component.ts [hunk 1]
```diff
@@ -1,33 +1,61 @@
...
-        scrollbarDirectiveRef.scrollToElement(`#nav-${ id }`, -8, 300);
-      }
-    }, 250);
+    const scrollbarDirectiveRef = this.componentRef?.directiveRef;
+    if (!scrollbarDirectiveRef) return;
+    const scrollbarElement = (scrollbarDirectiveRef.elementRef as ElementRef<HTMLElement>).nativeElement;
+    const menuItemEl = scrollbarElement.querySelector<HTMLElement>(`#nav-${ id }`);
+
+    if (menuItemEl && ((menuItemEl.offsetTop + menuItemEl.offsetHeight) >= (scrollbarElement.offsetHeight + scrollbarElement.scrollTop)
+      || menuItemEl.offsetTop - scrollbarElement.scrollTop <= 0)) {
```
Comment (ThomasJuster) [inline src/app/core/components/left-menu/left-menu.component.ts:52]: To me the early return a bit upper was a nice touch to avoid extra parenthesis in this big-enough condition

File: src/app/core/components/left-menu/left-menu.component.ts [hunk 2]
```diff
@@ -1,33 +1,61 @@
...
   templateUrl: './left-menu.component.html',
   styleUrls: [ './left-menu.component.scss' ]
 })
-export class LeftMenuComponent {
+export class LeftMenuComponent implements OnDestroy {
   @ViewChild(PerfectScrollbarComponent, { static: false }) componentRef?: PerfectScrollbarComponent;
 
   isNavThemeDark = false;
 
+  subscription = merge(
```
Comment (ThomasJuster) [inline src/app/core/components/left-menu/left-menu.component.ts:20]: I think subscriptions should be private

File: src/app/core/components/left-menu/left-menu.component.html [hunk 3]
```diff
@@ -1,4 +1,4 @@
 <alg-left-header></alg-left-header>
```
Comment (ThomasJuster) [inline src/app/core/components/left-menu/left-menu.component.html:1]: I have an issue with here:
1. As usual user, visit [this page](https://dev.algorea.org/branch/bugfix/left-menu-scroll-to-element/en/#/skills/by-id/1133373964112078654;path=3000,3002;attempId=0/details)
2. Under "skill for delete", I have the two children "Sub skill" and "sub skill 2" that are appended at the same level as their parent

image

Maybe if you rebase your branch the problem will disappear, can you check?

**Review by ThomasJuster — COMMENTED** [review]
:+1:

File: src/app/core/components/left-menu/left-menu.component.html (hunk 3 above)
Comment (Iloveall) [reply src/app/core/components/left-menu/left-menu.component.html:1]: Yes, this problem has been fixed in master

File: src/app/core/components/left-menu/left-menu.component.ts (hunk 2 above)
Comment (Iloveall) [reply src/app/core/components/left-menu/left-menu.component.ts]: Fixed

File: src/app/core/components/left-menu/left-menu.component.ts (hunk 1 above)
Comment (Iloveall) [reply src/app/core/components/left-menu/left-menu.component.ts]: Fixed

**Review by ThomasJuster — APPROVED** [review]
