### PR TITLE
Fix pending request

### LINKED ISSUE #236: Pending request loading indefinitely
Bug: on the "group you manage" root page `/#/groups/managed`, pending request pane loads indefinitely (without doing any request).

### PR DESCRIPTION
**Pull request by GabrielVidal1**
Fixes #236 
I change the way the data is fetch and updated to match the structure of the fetching done in the group members list component (mainly to handle the sorting of the table in a proper way).

### CODE REVIEW

File: src/app/modules/group/components/pending-request/pending-request.component.ts [hunk 1]
```diff
@@ -49,15 +51,78 @@ export class PendingRequestComponent implements OnInit, OnChanges {
...
-  status: 'loading' | 'loaded' | 'empty' |'error' = 'loading';
+
+  state: 'fetching' | 'ready' |'error' = 'fetching';
 
   ongoingActivity: Activity = 'none';
 
+  private dataFetching = new Subject<{ groupId?: string, includeSubgroup: boolean, sort: string[] }>();
+
+  private dataUpdating = new Subject<{ action: Action, requests: PendingRequest[] }>();
+
```
Comment (smadbe) [inline src/app/modules/group/components/pending-request/pending-request.component.ts:62]: Always complete subjects on destroy.

File: src/app/modules/group/components/pending-request/pending-request.component.ts [hunk 2]
```diff
@@ -49,15 +51,78 @@ export class PendingRequestComponent implements OnInit, OnChanges {
...
   collapsed = true;
-  status: 'loading' | 'loaded' | 'empty' |'error' = 'loading';
+
+  state: 'fetching' | 'ready' |'error' = 'fetching';
 
   ongoingActivity: Activity = 'none';
 
+  private dataFetching = new Subject<{ groupId?: string, includeSubgroup: boolean, sort: string[] }>();
+
+  private dataUpdating = new Subject<{ action: Action, requests: PendingRequest[] }>();
```
Comment (smadbe) [inline src/app/modules/group/components/pending-request/pending-request.component.ts:61]: When reading it the term `dataUpdating` is not clear (looks like it is the same as data fetching).
...
Now I've read what we do with them:
It is quite messy. Actually, your two subjects update the same state, so they cannot really be separated as they may conflict. (more comments below)

File: src/app/modules/group/components/pending-request/pending-request.component.ts [hunk 3]
```diff
@@ -49,15 +51,78 @@ export class PendingRequestComponent implements OnInit, OnChanges {
...
+        this.ongoingActivity = state.activity;
+        if (isReady(state)) {
+          this.displayResponseToast(
+            this.parseResults(state.data),
+            state.action === 'accept' ? 'accept' : 'reject', // still use a matching as it is "by coincidence" that the type of verb match
+            state.action === 'accept' ? 'accepted' : 'declined'
+          );
+          this.selection = [];
+          this.dataFetching.next({ groupId: this.groupId, includeSubgroup: this.includeSubgroup, sort: this.currentSort });
+        }
```
Comment (smadbe) [inline src/app/modules/group/components/pending-request/pending-request.component.ts:116]: I already explained that the ideal "subscribe" just take its input and put it in a instance variable. We are quite far from this here 😁. As a result it is quite messy and I cannot say at all if the logic is correct. As this class has many different scenarios and not so easy to test by hand, the code logic should be straightforward so that it can be checked by reading code.
Having these two dependent subject modifying the same state makes it very hard to validate.

File: src/app/modules/group/components/pending-request/pending-request.component.ts [hunk 4]
```diff
@@ -49,15 +51,78 @@ export class PendingRequestComponent implements OnInit, OnChanges {
...
+      },
+      err => {
+        this.state = 'ready';
+        this.processRequestError(err);
+        this.ongoingActivity = 'none';
```
Comment (smadbe) [inline src/app/modules/group/components/pending-request/pending-request.component.ts:121]: We can see that this var is in "conflict" with the state, it is not really independent of it (the html has `state === 'fetching' || ongoingActivity !== 'none'"` which shows this as well)

File: src/app/modules/group/components/pending-request/pending-request.component.html [hunk 5]
```diff
@@ -8,115 +8,122 @@
...
+    <div class="pending-request-container" #noError>
+      <alg-grid
+        *ngIf="requests.length > 0"
+        [selectedColumns]="columns"
+        [columns]="columns"
+        [data]="requests"
+        [groupInfo]="panel"
+        [(selection)]="selection"
+        (sort)="onCustomSort($event)"
+        [loading]="state === 'fetching' || ongoingActivity !== 'none'"
```
Comment (smadbe) [inline src/app/modules/group/components/pending-request/pending-request.component.html:32]: The two cases were separated on purpose to just block the UI while the action was ongoing and, only if it required a refresh, refresh it completely. We could consider that this new behavior is acceptable (even if not as good).

**Review by smadbe — COMMENTED** [review]
I suggest I take the hand on this PR. That's not very easy to organize, that's why it was already in my own todo for a while.

File: src/app/modules/group/components/pending-request/pending-request.component.ts [hunk 6]
```diff
@@ -49,15 +51,78 @@ export class PendingRequestComponent implements OnInit, OnChanges {
...
+          if (this.requests.length > 0) this.collapsed = false;
+        }
+      },
+      _err => {
+        this.state = 'error';
+      }
+    );
+
+    this.dataUpdating.pipe(
+      switchMap(params =>
```
Comment (smadbe) [inline src/app/modules/group/components/pending-request/pending-request.component.ts:89]: Actually actions must not be switched-mapped... they cannot be cancelled or half-done if another one arrive (even if it is not really possible). 
The remark is valid for any such actions (in other components as well).

**Review by smadbe — CHANGES_REQUESTED** [review]
Actually, no need for me to take the hand on it. 
What you should do is keep the dataFetching subject, but remove the `dataUpdating` one. These actions still have to be as before, that was very clean and straightforward. Doing the refresh through the subject is good as it allows handling the different refresh triggers.

File: src/app/modules/group/components/pending-request/pending-request.component.html [hunk 7]
```diff
@@ -8,115 +8,122 @@
...
-                  </span>
-                  <span class="user-info-activity" *ngIf="rowData.user.grade">
-                    <em>Grade: {{ rowData.user.grade }}</em>
-                  </span>
-                  <!-- <div class="user-info-content">
-                    {{ rowData.user.content }}
-                  </div> -->
+        <ng-template #headerTemplate let-columns>
+          <tr>
+            <th style="width: 3.3333rem; background-color: #d3dbe7;"></th>
```
[the remark this answers is not in the document]
Comment (GabrielVidal1) [reply src/app/modules/group/components/pending-request/pending-request.component.html]: fixed

File: src/app/modules/group/components/pending-request/pending-request.component.ts (hunk 1 above)
Comment (GabrielVidal1) [reply src/app/modules/group/components/pending-request/pending-request.component.ts]: fixed

File: src/app/modules/group/components/pending-request/pending-request.component.ts (hunk 6 above)
Comment (GabrielVidal1) [reply src/app/modules/group/components/pending-request/pending-request.component.ts]: fixed

File: src/app/modules/group/components/pending-request/pending-request.component.ts (hunk 2 above)
Comment (GabrielVidal1) [reply src/app/modules/group/components/pending-request/pending-request.component.ts]: fixed, I removed it

File: src/app/modules/group/components/pending-request/pending-request.component.ts (hunk 3 above)
Comment (GabrielVidal1) [reply src/app/modules/group/components/pending-request/pending-request.component.ts]: I moved this part out of the dataUpdating subject back in the `onAcceptOrReject` function.

File: src/app/modules/group/components/pending-request/pending-request.component.ts (hunk 4 above)
Comment (GabrielVidal1) [reply src/app/modules/group/components/pending-request/pending-request.component.ts]: I managed to merge these two variables (`state` and `ongoingActivity`) by having the state being `'fetching' | 'accepting' | 'rejecting' | 'ready' |'error'`. This simplified most of the processes.

File: src/app/modules/group/components/pending-request/pending-request.component.html (hunk 5 above)
Comment (GabrielVidal1) [reply src/app/modules/group/components/pending-request/pending-request.component.html]: fixed

**Review by smadbe — CHANGES_REQUESTED** [review]
Don't hesitate to ask if it is not clear.

File: src/app/modules/group/components/pending-request/pending-request.component.ts [hunk 8]
```diff
@@ -205,7 +170,43 @@ export class PendingRequestComponent implements OnInit, OnChanges {
...
+            state.action === 'accept' ? 'accepted' : 'declined'
+          );
+          this.selection = [];
+          this.dataFetching.next({
+            groupId: state.refreshData.groupId,
+            includeSubgroup: state.refreshData.includeSubgroup,
+            sort: state.refreshData.sort
+          });
+        }
+      },
```
[the remark this answers is not in the document]
Comment (GabrielVidal1) [reply src/app/modules/group/components/pending-request/pending-request.component.ts]: I change this in later commits. I managed to get rid of the `ongoingActivity` entirely, this removed a lot of gray zones.

File: src/app/modules/group/components/pending-request/pending-request.component.ts [hunk 9]
```diff
@@ -205,7 +170,43 @@ export class PendingRequestComponent implements OnInit, OnChanges {
...
 
-    this.dataUpdating.next({ action: action, requests: this.selection });
+    merge(
+      of({
+        ...fetchingState(),
+        action: action,
+        activity: action === 'accept' ? 'accepting' : 'rejecting' as Activity,
+      }),
+      this.processRequests(action, this.selection)
+        .pipe(map(result => ({
```
[the remark this answers is not in the document]
Comment (GabrielVidal1) [reply src/app/modules/group/components/pending-request/pending-request.component.ts]: fixed

File: src/app/modules/group/components/pending-request/pending-request.component.ts [hunk 10]
```diff
@@ -154,30 +162,42 @@ export class PendingRequestComponent implements OnInit, OnChanges {
...
+
+    this.processRequests(action, this.selection).pipe(
+      map(result => ({
+        result: result,
+        action: action,
+        refreshData: { groupId: this.groupId, includeSubgroup: this.includeSubgroup, sort: this.currentSort },
+      }))
+    ).subscribe(
+      state => {
+        this.state = 'ready';
```
Comment (smadbe) [inline src/app/modules/group/components/pending-request/pending-request.component.ts:180]: This function and the switchMap on the subject conflicts a bit on updating the state. So it should be ok, but it is not really so straightforward to prove that there is no way to have a conflict in one scenario.
But that's ok :-)

**Review by smadbe — CHANGES_REQUESTED** [review]
👍  Few small remarks remaining.

File: src/app/modules/group/components/pending-request/pending-request.component.ts [hunk 11]
```diff
@@ -154,30 +162,42 @@ export class PendingRequestComponent implements OnInit, OnChanges {
   }
 
   onAcceptOrReject(action: Action): void {
```
[the remark this answers is not in the document]
Comment (GabrielVidal1) [reply src/app/modules/group/components/pending-request/pending-request.component.ts]: fixed

File: src/app/modules/group/components/pending-request/pending-request.component.ts [hunk 12]
```diff
@@ -154,30 +162,42 @@ export class PendingRequestComponent implements OnInit, OnChanges {
...
-          this.selection = [];
-        },
-        err => {
-          this.processRequestError(err);
-          this.ongoingActivity = 'none';
-        }
-      );
+
+    if (action === 'accept') this.state = 'accepting';
+    else this.state = 'rejecting';
```
[the remark this answers is not in the document]
Comment (GabrielVidal1) [reply src/app/modules/group/components/pending-request/pending-request.component.ts]: fixed

File: src/app/modules/group/components/pending-request/pending-request.component.ts [hunk 13]
```diff
@@ -154,30 +162,42 @@ export class PendingRequestComponent implements OnInit, OnChanges {
...
+        this.selection = [];
+
+        this.dataFetching.next({
+          groupId: state.refreshData.groupId,
+          includeSubgroup: state.refreshData.includeSubgroup,
+          sort: state.refreshData.sort
+        });
+      },
+      err => {
+        this.state = 'ready';
```
[the remark this answers is not in the document]
Comment (GabrielVidal1) [reply src/app/modules/group/components/pending-request/pending-request.component.ts:203]: fixed

File: src/app/modules/group/components/pending-request/pending-request.component.ts [hunk 14]
```diff
@@ -154,30 +162,42 @@ export class PendingRequestComponent implements OnInit, OnChanges {
...
-      );
+
+    if (action === 'accept') this.state = 'accepting';
+    else this.state = 'rejecting';
+
+    this.processRequests(action, this.selection).pipe(
+      map(result => ({
+        result: result,
+        action: action,
+        refreshData: { groupId: this.groupId, includeSubgroup: this.includeSubgroup, sort: this.currentSort },
```
[the remark this answers is not in the document]
Comment (GabrielVidal1) [reply src/app/modules/group/components/pending-request/pending-request.component.ts]: fixed, I removed it all together

**Review by smadbe — APPROVED** [review]
