### PR TITLE
fix auth by cookie on cross site for subdomains only

### LINKED ISSUE #507: Fix cookie problem on cross site
As discussed, investigate the fact the auth cookie is not taken into consideration when authenticating (even temp user) using cookies in a cross-domain scenario.

### PR DESCRIPTION
**Pull request by ThomasJuster**
Fixes #507 for requests across subdomains only, not cross-domain requests

### CODE REVIEW

File: src/app/shared/helpers/domain.ts [hunk 1]
```diff
@@ -0,0 +1,6 @@
+export function getDomain(href: string): string {
```
Comment (smadbe) [inline src/app/shared/helpers/domain.ts:1]: should it be called "getRootDomain"? From my point of view, the domain of `https://sub.example.com/api/stuff ` is `sub.example.com`, not `example.com`

File: src/app/shared/http-services/auth.http-service.ts [hunk 2]
```diff
@@ -20,10 +21,31 @@ const longAuthServicesTimeout = 10000;
...
+     * A cookie party is defined by its domain:
+     * - first-party cookies have domain "dev.algorea.org", "api.algorea.org" or "algorea.org"
+     * - third-party cookies have domain or "complete-other-site.com"
+     * Safari and Firefox both disable third-party cookies by default, and Chrome will in 2021 (but postponed for 2023)
+     * Since third-party cookies will be removed in a near future, we chose not to enable this type of authentication,
+     * making the 'same-site' policy always true.
+     */
+  } : undefined;
+  private requestConfig = appConfig.authType === 'cookies' ? {
+    withCredentials: !this.isSameDomain,
```
Comment (smadbe) [inline src/app/shared/http-services/auth.http-service.ts:42]: `withCredentials` looks safe to set in all cookie cases, same domain or not, as it just marks the request as having credentials. (and it might save us issue with future changes in browsers)

File: src/app/shared/http-services/auth.http-service.ts [hunk 3]
```diff
@@ -20,10 +21,31 @@ const longAuthServicesTimeout = 10000;
...
+    /**
+     * NOTE:
+     * withCredentials is necessary to allow cross-origin resources to set cookies, even if the resources share the same domain.
+     * For instance, dev.algorea.org calling api.algorea.org is a cross-origin request,
+     * but a cookie with domain "algorea.org" is a first-party cookie, see note on cookie_same_site.
+     */
```
Comment (smadbe) [inline src/app/shared/http-services/auth.http-service.ts:48]: From what I understand, you claim here that dev.algorea.org is cross-origin api.algorea.org so should use `withCredentials` but that the way `isSameDomain` is computed makes in true in this case.

File: src/app/shared/http-services/auth.http-service.ts [hunk 4]
```diff
@@ -20,10 +21,31 @@ const longAuthServicesTimeout = 10000;
...
     use_cookie: '1',
-    cookie_secure: appConfig.secure ? '1' : '0',
-    cookie_same_site: appConfig.sameSite ? '1' : '0',
+    cookie_secure: this.apiUrl.protocol === 'https:' || this.apiUrl.hostname === 'localhost' ? '1' : '0',
+    cookie_same_site: '1',
+    /**
+     * NOTE on cookie_same_site:
+     * The 'same-site' policy only applies for auth by third-party cookie.
+     * A cookie party is defined by its domain:
+     * - first-party cookies have domain "dev.algorea.org", "api.algorea.org" or "algorea.org"
```
Comment (smadbe) [inline src/app/shared/http-services/auth.http-service.ts:34]: this sentence is not clear. As written, it seems that in absolute first-party cookies are those with domain "dev.algorea.org", "api.algorea.org" or "algorea.org".

File: src/app/shared/interceptors/credentials.interceptor.ts [hunk 5]
```diff
@@ -0,0 +1,26 @@
...
+  private withCredentials = appConfig.authType === 'cookies' && !this.isSameOrigin;
+
+  constructor() {}
+
+  intercept(req: HttpRequest<unknown>, next: HttpHandler): Observable<HttpEvent<unknown>> {
+    if (!req.url.toLowerCase().startsWith(appConfig.apiUrl)) {
+      return next.handle(req);
+    }
+
+    return next.handle(req.clone({ withCredentials: this.withCredentials }));
```
Comment (smadbe) [inline src/app/shared/interceptors/credentials.interceptor.ts:24]: same remark about `withCredentials` as above.

**Review by smadbe — CHANGES_REQUESTED** [review]

File: src/app/shared/helpers/domain.ts (hunk 1 above)
Comment (ThomasJuster) [reply src/app/shared/helpers/domain.ts]: Fixed. It became dead code.

File: src/app/shared/http-services/auth.http-service.ts (hunk 2 above)
Comment (ThomasJuster) [reply src/app/shared/http-services/auth.http-service.ts]: Fixed.

File: src/app/shared/http-services/auth.http-service.ts (hunk 3 above)
Comment (ThomasJuster) [reply src/app/shared/http-services/auth.http-service.ts]: Fixed.

File: src/app/shared/http-services/auth.http-service.ts (hunk 4 above)
Comment (ThomasJuster) [reply src/app/shared/http-services/auth.http-service.ts]: I tried making the whole comment clearer

File: src/app/shared/http-services/auth.http-service.ts [hunk 6]
```diff
@@ -28,16 +28,35 @@ export class AuthHttpService {
...
-     * - third-party cookies have domain or "complete-other-site.com"
+     * NOTE on cookie_same_site and the cookie attribute "SameSite":
      * Safari and Firefox both disable third-party cookies by default, and Chrome will in 2021 (but postponed for 2023)
      * Since third-party cookies will be removed in a near future, we chose not to enable this type of authentication,
      * making the 'same-site' policy always true.
+     *
+     * NOTE on cookie party:
+     * A cookie party is determined by its "Domain" attribute, which defaults to the hostname.
+     * As defined by the MDN glossary, the domain represents an "authority", an organization to which belongs the cookie.
+     * In our case, the authority is "algorea.org".
```
Comment (smadbe) [inline src/app/shared/http-services/auth.http-service.ts:37]: It is more "for instance" than "In our case", this domain may change for this app.

**Review by smadbe — APPROVED** [review]
