### PR TITLE
Improves thread opening logic, fixes thread opening margin top bugs

### LINKED ISSUE #1225: Display forum thread next to task, not on top of it
## Overview
Currently the forum thread, when visible, is on top of the task. This prevent the user to interact with an instructor while trying to solve a task. Instead, display it next to the task, so reduce the size of the task when extending the forum.

### PR DESCRIPTION
**Pull request by Iloveall**
## Description

Fixes #1225

## Notes (out of scope, known isues, hints for reviewing code, ...)  (optional)

After fix `ExpressionChangedAfterItHasBeenCheckedError` I've found new issue:

CASE: 1
1. As usual user
2. Go to this [page](https://dev.algorea.org/en/activities/by-id/107818248417475126;path=899800937596940136,594266761627340815;attempId=0)
3. Then I click on open thread button
4. Then I do resize browser
5. Then I see the thread container doesn't align correct

CASE: 2
1. As usual user
2. Go to this [page](https://dev.algorea.org/en/activities/by-id/79334044945497051;path=;parentAttempId=0?watchedGroupId=6710944276987033666&watchUser=0)
3. Then I click on stop watching
4. Then I click on open thread button
5. Then I see the thread container doesn't align correct

## Test cases

- [ ] Case 1:
  1. Given I am the usual user
  2. When I go to [this page](https://dev.algorea.org/branch/feature/display-forum-thread-next-to-task/en/activities/by-id/784078458149384669;path=;attempId=0)
  3. And I click on open thread button
  4. Then I see the thread container is not overlayed the task

- [ ] Case 2:
  1. Given I am the usual user
  2. When I go to [this page](https://dev.algorea.org/branch/feature/display-forum-thread-next-to-task/en/activities/by-id/79334044945497051;path=;parentAttempId=0?watchedGroupId=6710944276987033666&watchUser=0)
  3. Then I click on stop watching mode
  4. And I click on open thread button
  5. Then I see the thread container is align correct

- [ ] Case 3:
  1. Given I am the usual user
  2. When I go to [this page](https://dev.algorea.org/branch/feature/display-forum-thread-next-to-task/en/activities/by-id/784078458149384669;path=;attempId=0)
  3. And I click on open thread button
  4. Then I do resize browser
  5. Then I see the thread container is align correct

### CODE REVIEW

File: src/app/modules/item/pages/item-by-id/item-by-id.component.ts [hunk 1]
```diff
@@ -279,6 +310,11 @@ export class ItemByIdComponent implements OnDestroy, BeforeUnloadComponent, Pend
 
   showItemThreadWidget = !!appConfig.forumServerUrl;
 
+  @HostListener('window:resize')
+  resize(): void {
+    this.contentContainerTop = this.contentContainer?.nativeElement.offsetTop || 0;
+  }
```
Comment (smadbe) [inline src/app/modules/item/pages/item-by-id/item-by-id.component.ts:316]: Cannot you put it in the `merge` you have added instead of repeating the same here? 
(with an event such as `fromEvent(window, 'resize')`)

**Review by smadbe — APPROVED** [review]

File: src/app/modules/item/pages/item-by-id/item-by-id.component.ts (hunk 1 above)
Comment (Iloveall) [reply src/app/modules/item/pages/item-by-id/item-by-id.component.ts]: Fixed
